package stand.battery.tx;

public enum ActiveFaultData {
	BUS_VOLT_AD_FLT, PACK_VOLT_AD_FLT, PACK_CUR_B_HI_AD_FLT, PACK_CUR_B_LO_AD_FLT, PACK_CUR_A_HI_AD_FLT,
	PACK_CUR_A_LO_AD_FLT, BD_UNDER_TEMP_FLT, SEC_STUCK_ON_FLT, INT_ISO_FLT, EXT_ISO_FLT, SEC_CONTA_OPEN_FLT,
	CONT_PCHG_SHORT_FLT, CONT1_DROPOUT_2ND_FLT, CONT1_DROPOUT_1ST_FLT, CONT_PCHG_RETRY_FLT, CONT_PCHG_FLT,
	REDUNDANT_CELLV_COMPARE_FLT, CONT2_STUCK_ON_FLT, NO_CHARGE_CUR_FLT, BD_OVER_TEMP_FLT, UNDER_TEMP_FLT, OVER_TEMP_FLT,
	FAN_CUR_LO_FLT, FAN_CUR_HI_FLT, MODULEV_TO_CELLV_COMPARE_FLT, CONT1_STUCK_ON_FLT, UNDER_VOLT_FLT_B,
	UNDER_VOLT_FLT_A, OVER_VOLT_FLT_B, OVER_VOLT_FLT_A, OVER_CURRENT_FLT, SPI_FLT, CONT2_DROPOUT_2ND_FLT,
	CONT2_DROPOUT_1ST_FLT, CONT1_STUCK_OPEN_FLT, CONT2_STUCK_OPEN_FLT, SEC_CONTB_OPEN_FLT, NO_PCU_DATA_FLT,
	OVER_CURRENT_REG_FLT, IN_12V_UNDER_VOLT_FLT, LO_DCHG_DURING_CHG_FLT, HI_DCHG_DURING_CHG_FLT, SLAVE_COMM_FLT,
	STRING_V_MISMATCH_FLT, IN_12V_UV_WARNING, HI_CONT_COIL_CUR_FLT, CV_CONNECTION_FLT, EXTREME_UNDER_VOLT_FLT,
	LO_CUR_CORRELATION_FLT, HI_CUR_CORRELATION_FLT, MAIN_CONT_OPEN_TIMEOUT, PTC_HEATER_FLT, PACK_TEMPERATURE_AD_FLT,
	MODULE_V_OUTLIER_FLT, UNREASONABLE_TEMP_FLT, HIGH_TEMP_DELTA_FLT, HIGH_CV_DELTA_FLT, NO_EPO_FLT, NO_AIN_CAL,
	NO_CONFIG, EXT_FAULT;
}
