package stand.t_45;
import com.ochafik.lang.jnaerator.runtime.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * --------------------- \u0421\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0430 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u043e\u0432 \u0421\u043e\u043c-\u043f\u043e\u0440\u0442\u0430<br>
 * <i>native declaration : line 94</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ParamComPort extends Structure<ParamComPort, ParamComPort.ByValue, ParamComPort.ByReference > {
	/** \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438 \u0434\u0430\u043d\u043d\u044b\u0445 */
	public int BaudRate;
	/** \u0447\u0438\u0441\u043b\u043e \u0431\u0438\u0442\u043e\u0432 \u0434\u0430\u043d\u043d\u044b\u0445 */
	public byte BiteSize;
	/** \u0441\u0445\u0435\u043c\u0430 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044f \u0447\u0435\u0442\u043d\u043e\u0441\u0442\u0438 */
	public byte Parity;
	/** \u0447\u0438\u0441\u043b\u043e \u0441\u0442\u043e\u043f\u043e\u0432\u044b\u0445 \u0431\u0438\u0442 */
	public byte StopBits;
	public ParamComPort() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("BaudRate", "BiteSize", "Parity", "StopBits");
	}
	/**
	 * @param BaudRate \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438 \u0434\u0430\u043d\u043d\u044b\u0445<br>
	 * @param BiteSize \u0447\u0438\u0441\u043b\u043e \u0431\u0438\u0442\u043e\u0432 \u0434\u0430\u043d\u043d\u044b\u0445<br>
	 * @param Parity \u0441\u0445\u0435\u043c\u0430 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044f \u0447\u0435\u0442\u043d\u043e\u0441\u0442\u0438<br>
	 * @param StopBits \u0447\u0438\u0441\u043b\u043e \u0441\u0442\u043e\u043f\u043e\u0432\u044b\u0445 \u0431\u0438\u0442
	 */
	public ParamComPort(int BaudRate, byte BiteSize, byte Parity, byte StopBits) {
		super();
		this.BaudRate = BaudRate;
		this.BiteSize = BiteSize;
		this.Parity = Parity;
		this.StopBits = StopBits;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected ParamComPort newInstance() { return new ParamComPort(); }
	public static ParamComPort[] newArray(int arrayLength) {
		return Structure.newArray(ParamComPort.class, arrayLength);
	}
	public static class ByReference extends ParamComPort implements Structure.ByReference {
		
	};
	public static class ByValue extends ParamComPort implements Structure.ByValue {
		
	};
}
