package stand.semikron.tx;

import java.util.HashMap;
import java.util.Map;

public class ErrorCodes {
	private static Map<Integer, String> errorCodes = new HashMap<>();

	static {
		errorCodes = new HashMap<>();
		errorCodes.put(0, "No error");
		errorCodes.put(1, "Short circuit (DSCP) L1 TOP");
		errorCodes.put(2, "Short circuit (DSCP) L1 BOT");
		errorCodes.put(3, "Short circuit (DSCP) L2 TOP");
		errorCodes.put(4, "Short circuit (DSCP) L2 BOT");
		errorCodes.put(5, "Short circuit (DSCP) L3 TOP");
		errorCodes.put(6, "Short circuit (DSCP) L3 BOT");
		errorCodes.put(7, "Undervoltage (UVP) L1 TOP");
		errorCodes.put(8, "Undervoltage (UVP) L1 BOT");
		errorCodes.put(9, "Undervoltage (UVP) L2 TOP");
		errorCodes.put(10, "Undervoltage (UVP) L2 BOT");
		errorCodes.put(11, "Undervoltage (UVP) L3 TOP");
		errorCodes.put(12, "Undervoltage (UVP) L3 BOT");
		errorCodes.put(13, "Overcurrent phase L1 POS");
		errorCodes.put(14, "Overcurrent phase L1 NEG");
		errorCodes.put(15, "Overcurrent phase L2 POS");
		errorCodes.put(16, "Overcurrent phase L2 NEG");
		errorCodes.put(17, "Overcurrent phase L3 POS");
		errorCodes.put(18, "Overcurrent phase L3 NEG");
		errorCodes.put(19, "DC link overvoltage");
		errorCodes.put(20, "Supply undervoltage");
		errorCodes.put(21, "DCB overtemp. L1 (HW)");
		errorCodes.put(22, "DCB overtemp. L2 (HW)");
		errorCodes.put(23, "DCB overtemp. L3 (HW)");
		errorCodes.put(24, "PCB overtemperature (HW)");
		errorCodes.put(25, "Motor temp. sensor error");
		errorCodes.put(26, "Resolver track lost");
		errorCodes.put(27, "Resolver track high");
		errorCodes.put(28, "Resolver degenerated");
		errorCodes.put(29, "Resolver config parity");
		errorCodes.put(30, "Resolver phase high");
		errorCodes.put(31, "Resolver speed high");
		errorCodes.put(32, "Resolver sin/cos fail");
		errorCodes.put(33, "Resolver sin/cos high");
		errorCodes.put(34, "Resolver sin/cos low");
		errorCodes.put(35, "Resolver sin/cos cut");
		errorCodes.put(39, "HVIL missing");
		errorCodes.put(43, "DC link undervoltage");
		errorCodes.put(44, "DC link overvoltage");
		errorCodes.put(48, "PCB overtemperature (SW)");
		errorCodes.put(50, "Motor overtemperature");
		errorCodes.put(51, "Motor overspeed");
		errorCodes.put(52, "FPGA communication failed");
		errorCodes.put(54, "CAN A node guard expired");
		errorCodes.put(55, "CAN bus A off");
		errorCodes.put(58, "CAN bus A bitrate ");
		errorCodes.put(60, "CAN bus A channel");
		errorCodes.put(62, "CAN bus A general");
		errorCodes.put(63, "CAN B node guard expired");
		errorCodes.put(64, "CAN bus B off");
		errorCodes.put(67, "CAN bus B bitrate ");
		errorCodes.put(69, "CAN bus B channel");
		errorCodes.put(71, "CAN bus B general");
		errorCodes.put(72, "Encoder signal deg.");
		errorCodes.put(73, "Watchdog occurred");
		errorCodes.put(74, "D current difference");
		errorCodes.put(75, "Q current difference");
		errorCodes.put(78, "Timing exceeded");
		errorCodes.put(79, "Initialization failed");
		errorCodes.put(80, "Table version wrong");
		errorCodes.put(81, "Table checksum flash");
		errorCodes.put(100, "Enable denied speed");
		errorCodes.put(101, "Fatal error");
		errorCodes.put(102, "SPO / External Error");
		errorCodes.put(103, "Inverter init failed");
		errorCodes.put(104, "CAN initialization failed");
		errorCodes.put(105, "License invalid");
		errorCodes.put(106, "Scope init failed");
		errorCodes.put(110, "Table not initialized");
		errorCodes.put(111, "Division by zero");
		errorCodes.put(112, "Table positive Id value");
		errorCodes.put(114, "PTC resistor is zero");
		errorCodes.put(116, "Sample mode undefined");
		errorCodes.put(117, "Position init failed");
		errorCodes.put(118, "PWM modulation invalid");
		errorCodes.put(119, "Float out of range");
		errorCodes.put(120, "Parameter read failed (store)");
		errorCodes.put(121, "Parameter read failed (format)");
		errorCodes.put(122, "Parameter table checksum ");
		errorCodes.put(123, "ASC overvoltage");
		errorCodes.put(126, "Max. torque table invalid");
		errorCodes.put(127, "Max. current [0x2100]");
		errorCodes.put(129, "Adapt torque [0x2499]");
		errorCodes.put(135, "Init error log failed");
		errorCodes.put(136, "PLL not locked");
		errorCodes.put(137, "PLL not synchronized");
		errorCodes.put(138, "PLL [0x2173]-[0x2174]");
		errorCodes.put(139, "EEPROM init failed");
		errorCodes.put(141, "Invalid device information");
		errorCodes.put(142, "Motor type [0x2119]");
		errorCodes.put(143, "PWM Frequency [0x2077]");
		errorCodes.put(144, "External temp. sensor [0x214A]");
		errorCodes.put(145, "Read hour counter failed");
		errorCodes.put(146, "Write hour counter failed");
		errorCodes.put(147, "Max cutback limits");
		errorCodes.put(148, "Min cutback limits");
		errorCodes.put(150, "Kp is wrong [0x21B5]");
		errorCodes.put(151, "Ki is wrong [0x21B6]");
		errorCodes.put(152, "Cutback bit is invalid");
		errorCodes.put(153, "Current Sensor 1 Offset");
		errorCodes.put(154, "Current Sensor 3 Offset");
		errorCodes.put(155, "Cutback I2T [2513] [2514]");
		errorCodes.put(156, "Current sensor offset calib.");
		errorCodes.put(157, "Invalid ASC state feedback");
		errorCodes.put(158, "Control mode not supported");
		errorCodes.put(159, "Junction overtemperature");
		errorCodes.put(160, "Torque limitation supervision");
		errorCodes.put(161, "Undervoltage supply input ");
		errorCodes.put(162, "Current Sensor 2 Offset");
		errorCodes.put(163, "Kirchhoff current check");
		errorCodes.put(164, "DCB plausibility check");
		errorCodes.put(165, "Resolver loss of signal");
		errorCodes.put(166, "Dead time currents conflict");
		errorCodes.put(167, "S-shape initialization");
		errorCodes.put(168, "Memory test failed");
		errorCodes.put(169, "Stack overflow detected");
		errorCodes.put(170, "Angle offset uncalibrated");
		errorCodes.put(174, "Timing exceeded 1ms");
		errorCodes.put(175, "Store to EEPROM failed");
		errorCodes.put(176, "Init event log failed");
		errorCodes.put(178, "Cutback active while PS calib.");
		errorCodes.put(179, "Invalid CAN parameter");
		errorCodes.put(180, "Ext. temp. 2 Error");
		errorCodes.put(181, "Ext. temp. 2 overtemp.");
		errorCodes.put(182, "Table Motor Type");
		errorCodes.put(183, "Id boost cutback conflict");
		errorCodes.put(184, "CANopen message timeout");
		errorCodes.put(185, "CANopen message counter");
		errorCodes.put(186, "Invalid Poles");
		errorCodes.put(187, "Comp. observer config");
		errorCodes.put(188, "Voltage drop comp. [0x21ED-1]");
		errorCodes.put(190, "PS calib high current");
		errorCodes.put(191, "PS calib low current");
		errorCodes.put(192, "PS calib ramp up time low");
		errorCodes.put(193, "PS calib speed 1 high or 0");
		errorCodes.put(194, "PS calib speed ramp up low");
		errorCodes.put(195, "PS calib speed 2 high or 0");
		errorCodes.put(196, "PS calib wrong motor type");
		errorCodes.put(197, "PS calib few measurements");
		errorCodes.put(198, "PS calib high current error");
		errorCodes.put(199, "PS calib not rotating");
		errorCodes.put(200, "PS calib bad rotating sense");
		errorCodes.put(201, "PS calib bad speed 1");
		errorCodes.put(202, "PS calib bad speed 2");
		errorCodes.put(203, "PS calib bad speed and sense ");
		errorCodes.put(207, "PS calib time out speed (fine)");
		errorCodes.put(209, "PS calib stop time out");
		errorCodes.put(211, "PS calib low speed 1");
		errorCodes.put(212, "PS calib low speed 2");
		errorCodes.put(213, "PS calib timeout 0 current");
		errorCodes.put(215, "PS calib failed speed 1 (fine)");
		errorCodes.put(216, "PS calib failed speed 2 (fine)");
		errorCodes.put(217, "PS calib over speed 1 ");
		errorCodes.put(219, "PS calib general error");
		errorCodes.put(220, "HW code limit exceeded");
		errorCodes.put(221, "Part number FW not valid");
		errorCodes.put(222, "Part number BL is not valid");
		errorCodes.put(223, "S-shape initialization");
		errorCodes.put(224, "J1939 debug request timeout");
		errorCodes.put(225, "Unexpected shut-down");
		errorCodes.put(226, "Resolver plausibility check");
		errorCodes.put(227, "Indexes [0x2069]/[0x2111]>1");
		errorCodes.put(228, "Inverter type not supported");
		errorCodes.put(229, "HW code data inconsistent");
		errorCodes.put(230, "Invalid control mode requested");
		errorCodes.put(231, "Reading UDS config failed");
		errorCodes.put(232, "Dc link voltage sensor error");
		errorCodes.put(233, "ADC ref. voltage error");
		errorCodes.put(234, "Incompatible PDO map");
		errorCodes.put(235, "DC link power selection [2029]");
		errorCodes.put(236, "Encoder lines [0x2188] < 1");
		errorCodes.put(237, "Timing exceeded main loop");
		errorCodes.put(238, "NMT command disabled the PWM");
		errorCodes.put(750, "J1939 nominal torque");
		errorCodes.put(751, "J1939 stuck speed/torque req.");
		errorCodes.put(752, "J1939 DC power limits");
		errorCodes.put(753, "CAN J1939 enable message");
		errorCodes.put(754, "J1939 speed/torque timeout");
		errorCodes.put(755, "AC over current error");
		errorCodes.put(756, "Current gain mismatch 2 3");
		errorCodes.put(757, "Current gain mismatch 1 2");
		errorCodes.put(758, "UDS parameter mismatch");
		errorCodes.put(759, "DC link power ctrl. conflict");
	}

	public static String getErrorByCode(int code) {
		return errorCodes.get(code);

	}
}
